---
title: "Client Report - The War With Star Wars"
subtitle: "Course DS 250"
author: "JT Twiggs"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

### Paste in a template

```{python}
import pandas as pd
import plotly_express as px
import numpy as np
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, accuracy_score, precision_score

from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import HistGradientBoostingClassifier
from catboost import CatBoostClassifier

```

### QUESTION|TASK 1

__Create 2-3 charts that evaluate potential relationships between the home variables and before1980. Explain what you learn from the charts that could help a machine learning algorithm.__
```{python}
star = pd.read_csv('StarWars.csv', 
                   encoding ='latin1',
                   skiprows = 1)

```

```{python}
#fix column names
star.columns = [
  'id',

  'seen_a_star_wars_movie',
  'fan_of_star_wars',

  'seen_ep_1','seen_ep_2', 
  'seen_ep_3', 'seen_ep_4', 
  'seen_ep_5', 'seen_ep_6',

  'ep_1_rank', 'ep_2_rank', 
  'ep_3_rank', 'ep_4_rank', 
  'ep_5_rank', 'ep_6_rank',

  'han_solo_rated',
  'luke_rated', 'leia_rated', 'anakin_rated', 'obi_wan_rated',
  'palpatine_rated', 'vader_rated', 'lando_rated', 'boba_fett_rated',
  'C-3P0_rated', 'R2_rated', 'jar_jar_rated', 'padme_rated',
  'yoda_rated', 

  'who_shot_first',
  'know_expanded_universe',
  'expanded_universe_fan',
  'star_trek_fan',

  'gender', 
  'age', 
  'income', 
  'edu',
  'region'
  ]

```


### QUESTION|TASK 2

__Clean and format the data so that it can be used in a machine learning model. As you format the data, you should complete each item listed below. In your final report provide example(s) of the reformatted data with a short description of the changes made.__

```{python}
# one-hot encode the whole dataset in one go
def one_hot(x):
  # read through the column names
  for col in x:

    # record the number of possible answers
    responses = x[col].value_counts().count()

    # concat with get_dummies for all non yes/no questions, avoiding the id column
    if responses > 2 and responses < 20 :
      x = pd.concat([x, pd.get_dummies(x[col], prefix = str(col), dtype= np.int64)], axis = 1) 
      x.drop(col, axis = 1, inplace = True)

    # deal with the yes/no or short list responses
    elif responses <= 2:

      # list the available option, make sure all yes/no's have yes == 1, no == 0
      option_1 = x[col].value_counts().index.tolist()[0]
      if option_1 == 'Yes':
        x[col] = x[col].apply(lambda value: int(1 if value == option_1 else 0)) 

      elif option_1 == 'No':
        x[col] = x[col].apply(lambda value: int(0 if value == option_1 else 1)) 

      # odd column out, only 2 answers but still needs a concat and get_dummies
      elif option_1 == 'Female':
        x = pd.concat([x, pd.get_dummies(x[col], prefix = str(col), dtype= np.int64)], axis = 1) 
        x.drop(col, axis = 1, inplace = True)

      # all the 'have you seen episode ...' questions
      else:
        x[col] = x[col].apply(lambda value: int(1 if value == option_1 else 0)) 
    else:
      continue
  return pd.DataFrame(x)

star_coded = one_hot(star)
star_coded #now we have an one-hot encoded starwars dataset
```

### TASK 2a.

__Filter the dataset to respondents that have seen at least one film__
```{python}
# filter by if they have seen a movie or if they said they saw a specific episode
seen_one = star_coded.query('seen_ep_1 == 1 | seen_ep_2 == 1 | seen_ep_3 == 1 | seen_ep_4 == 1 | seen_ep_5 == 1 | seen_ep_6 == 1')

print(seen_one.count())
```

### TASK 2b.

__Create a new column that converts the age ranges to a single number. Drop the age range categorical column__

### TASK 2c.

__Create a new column that converts the education groupings to a single number. Drop the school categorical column__

### TASK 2d.

__Create a new column that converts the income ranges to a single number. Drop the income range categorical column__

### TASK 2e.

__Create your target (also known as “y” or “label”) column based on the new income range column__
```{python}
# our target is fans who earn above 50k, so we need to make a new column
star_coded['above_50k'] = (star_coded['income_$50,000 - $99,999'] == 1) | (star_coded['income_$100,000 - $149,999'] == 1) | (star_coded['income_$150,000+'] == 1)

star_coded['above_50k'] = star_coded['above_50k'].astype(int)

star_coded.loc[star_coded['above_50k'] == 0, 'above_50k'] = 0
```

### TASK 2f.

__One-hot encode all remaining categorical columns__
```{python}
# completed in the one-hot function
```


### QUESTION|TASK 3

__Validate that the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article.__

#### figure 1
```{python}
#for the sake of recreating graphic 1:
seen_all = star_coded.query('seen_ep_1 == 1 and seen_ep_2 == 1 and seen_ep_3 == 1 and seen_ep_4 == 1 and seen_ep_5 == 1 and seen_ep_6 == 1')
print(seen_all.count())

#narrow the dataset to the good stuff
seen_all_prep = seen_all[['id', 'ep_1_rank_1.0', 'ep_2_rank_1.0', 'ep_3_rank_1.0', 'ep_4_rank_1.0', 'ep_5_rank_1.0', 'ep_6_rank_1.0', ]]

#change the column names
seen_all_prep.columns = [
  'id',

  'The Phantom Menace',
  'Attack of the Clones',

  'Revenge of the Sith','A New Hope', 
  'The Empire Strikes Back', 'Return of the Jedi']

 #Melt the DataFrame
vis1 = pd.melt(seen_all_prep, id_vars=['id'], var_name='fav_ep', value_name='yes')

# Filter the DataFrame
vis1 = vis1[vis1['yes'] == 1]

# Group and count occurrences
vis1_data = vis1.groupby('fav_ep').size().reset_index(name='count')

# Calculate the total count
total_value = vis1_data['count'].sum()

# Calculate the percentage
vis1_data['percentage'] = vis1_data['count'] / total_value * 100

vis1_data['percentage'] = vis1_data['percentage'].round()
# Display the DataFrame with percentages
print(vis1_data)

```

```{python}
# build the plot
fig = px.bar(vis1_data, x='fav_ep', y='percentage', title="What's the Best 'Star Wars' Movie? ", labels={'fav_ep': 'Favorite Episode', 'percentage': 'Percentage'})

# Show the plot
fig.show()
```

```{python}
seen_one #who shot first graphic 2

shot_first_prep = seen_one[['id', 'who_shot_first_Greedo', 'who_shot_first_Han', "who_shot_first_I don't understand this question"]]

# fix column names
shot_first_prep.columns = [
  'id',
  'Greedo',
  'Han',
  "I don't understand this question"]

vis2 = pd.melt(shot_first_prep, id_vars=['id'], var_name='answer_choice', value_name='response')

# Filter out rows where 'presence' is 0
vis2 = vis2[vis2['response'] == 1]

# make the second visual
# Group and count occurrences
vis2_data = vis2.groupby('answer_choice').size().reset_index(name='count')

# Calculate the total count
total_value2 = vis2_data['count'].sum()

# Calculate the percentage
vis2_data['percentage'] = vis2_data['count'] / total_value2 * 100

vis2_data['percentage'] = vis2_data['percentage'].round()
# Display the DataFrame with percentages
print(vis2_data)
```

```{python}
# build the plot
fig2 = px.bar(vis2_data, x='answer_choice', y='percentage', title="Who Shot First?", labels={'answer_choice': 'Response', 'percentage': 'Percentage'}, )

# Show the plot
fig2.show()

```

### QUESTION|TASK 4

__Build a machine learning model that predicts whether a person makes more than $50k. Describe your model and report the accuracy.__

```{python}
# lets use the star_coded dataframe for this
X = star_coded.drop(['id', 'income_$0 - $24,999', 'income_$25,000 - $49,999', 'income_$50,000 - $99,999', 'income_$100,000 - $149,999', 'income_$150,000+','above_50k'], axis=1)
  
y = star_coded.above_50k
```

```{python}
# 70/30 train/test ratio for the dataset
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=.3)
```


```{python}
model = CatBoostClassifier()

# Create and train the models with a RandomForestClassifier
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"model: {model}")
print(f"Accuracy: {accuracy}")
```



The catBoostClassifier was consistently the most accurate model (~ 60 - 65%) to test the dataset with. All income and id columns were removed to ensure more accurate testing of the data.


### Questions and Tasks (Stretch)

__1. Build a machine learning model that predicts whether a person makes more than $50k. With accuracy of at least 65%. Describe your model and report the accuracy.__

The model that I made in the previous task consistently scored between 64% and 66% for accuracy when ran in the environment. I'm not sure why the score drops so dramatically in the preview.