---
title: "Client Report - What's In a Name?"
subtitle: "Course DS 250"
author: "JT Twiggs"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

### Paste in a template

```{python}
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

From this assignment, I think it was interesting to learn that most biblical names are significantly less popular than I thought. My name, Thomas, is also significantly less common than I thought. Maybe it's just where I grew up, but I knew quite a few people who I shared a name with. I also saw that popular names used in movies and current celebrities also affect how often a name is used. It is cool to see how quickly you can make a simple query and graph it to learn something new.

```{python}
# downloading the names_year.csv
nam = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
nam.head()
```

__Highlight the Questions and Tasks__

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

```{python}
t = nam.query('name == "Thomas"')
t
```

```{python}
tom = px.line(t, x = 'year', y = 'Total')

tom.add_vline(2001, line_width = 2, line_dash = 'dash', line_color = 'red')
tom.update_layout(title = 'Number of People Named Thomas'),
tom.add_annotation(x = 2001, y = 30000, text = "My birth year: 2001")

tom.show()
```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

Because the name 'Brittany' really spiked up between the 80s and 90s, I would have to assume that anyone named Brittany is between the ages of 30 - 45. I wouldn't guess anything higher than 45, and seeing how few people are named that after the year 2000, I wouldn't guess lower than 30. I would immediately assume someone named Brittany is in their late 30s.

```{python}
b = nam.query('name == "Brittany"')

brit = px.line(b, x = 'year', y = 'Total')
brit.update_layout(title = 'Number of People Named Brittany'),

brit.show()
```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

Every single name across these 4 got a huge decrease in popularity from the 50s-80s. I'm honestly surprised that Mary was so popular when compared with other bible names, granted, Martha wasn't ever a popular name when compared with Mary. Every name had a count of less than 10k by the year 2000.

```{python}
bib = nam.query('(name == "Mary" | name == "Martha" | name == "Peter" | name == "Paul") and year >= 1920 and year <= 2000')

bible = px.line(bib, x = 'year', y = 'Total', color = 'name')
bible.update_layout(title = 'Biblical Name Count')

bible.show()
```

## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

We are going to check out the name 'Leonardo' based off of the celebrity actor Leonardo DiCaprio and the acclaimed film 'Titanic'. It does look like there was an increase in the popularity of the name following this movie's release. There are certainly other factors that could be at play, but I think it would be funny if this is a major reason for the name becoming popular.
```{python}
l = nam.query('name == "Leonardo" and year >= 1970')

leo = px.line(l, x = 'year', y = 'Total')
leo.add_vline(x = 1997, line_width = 2, line_dash = 'dash')
leo.add_annotation(x = 1997, y = 1300, text = "Film 'Titanic' Released")
leo.update_layout(title = 'Number of People Named Leonardo')

leo.show()
```

## QUESTIONS AND TASKS (STRETCH)

__Reproduce the chart Elliot using the data from the names_year.csv file.__

```{python}
el = nam.query('name == "Elliot" and year >= 1950')

elliot = px.line(el, x = 'year', y = 'Total', color = 'name')
# Adding the red lines for releases
elliot.add_vline(x = 1982, line_width = 2, line_dash = 'dash', line_color = 'red')
elliot.add_vline(x = 1985, line_width = 2, line_dash = 'dash', line_color = 'red')
elliot.add_vline(x = 2002, line_width = 2, line_dash = 'dash', line_color = 'red')
# Adding the annotations
elliot.add_annotation(
  x = 1982
, y = 1300
, text = "<b> E.T Released </b>" 
, font = dict(size = 11)
, opacity= 0.9
, showarrow = False
, xshift= -43)

elliot.add_annotation(
  x = 1985
, y = 1300
, text = "<b> Second Release </b>"
, font = dict(size = 11)
, opacity= 0.9
, showarrow = False
, xshift = 52)

elliot.add_annotation(
  x = 2002, y = 1300
, text = "<b> Third Release </b>"
, font = dict(size = 11)
, opacity= 0.9
, showarrow = False
, xshift = 44)

# Adding the title
elliot.update_layout(
  title = '<b>Elliot... What?</b>'
)

# Showing the graphic
elliot.show()
```